export const coursesPredictionResult = [
  {
    name: 'Introduction to Information Systems',
    credits: 3,
    subjectArea: 'information_systems',
    description: 'An introduction to the discipline of information systems and the foundations for future IS modules.',
    page: 4,
  },
  {
    name: 'Programming',
    credits: 9,
    subjectArea: 'computer_science',
    description: 'Introduction to programming using an object-oriented language (Java), covering core concepts, data structures, and basic software development.',
    page: 8,
  },
  {
    name: 'Mathematics for IS',
    credits: 9,
    subjectArea: 'quantitative_methods',
    description: 'Mathematical methods including calculus, linear algebra, and optimization used in economic and IS contexts.',
    page: 11,
  },
  {
    name: 'Foundations of Business Administration',
    credits: 9,
    subjectArea: 'business_administration',
    description: 'An introductory overview of business administration including investment and financing decisions.',
    page: 14,
  },
  {
    name: 'Data Management',
    credits: 6,
    subjectArea: 'information_systems',
    description: 'Concepts and methods for data modeling, data concepts, DV concepts, and relational database implementation using SQL (with notes on NoSQL).',
    page: 17,
  },
  {
    name: 'Data Structures and Algorithms',
    credits: 9,
    subjectArea: 'computer_science',
    description: 'Fundamental data structures and algorithms with analysis of efficiency and implementation.',
    page: 20,
  },
  {
    name: 'Operations Research',
    credits: 6,
    subjectArea: 'quantitative_methods',
    description: 'Mathematical optimization methods including graphs, linear programming, nonlinear programming, and decision theory.',
    page: 23,
  },
  {
    name: 'Foundations of Accounting',
    credits: 9,
    subjectArea: 'business_administration',
    description: 'Foundations of internal and external accounting, including cost accounting and financial reporting.',
    page: 26,
  },
  {
    name: 'Process Management',
    credits: 6,
    subjectArea: 'information_systems',
    description: 'Modeling and managing business processes and ERP systems within organizations.',
    page: 30,
  },
  {
    name: 'Software Engineering',
    credits: 6,
    subjectArea: 'computer_science',
    description: 'Develop large software systems using UML, design patterns, and process models.',
    page: 33,
  },
  {
    name: 'Data and Probabilities',
    credits: 6,
    subjectArea: 'quantitative_methods',
    description: 'Descriptive statistics, probability theory, and data analysis including software tools.',
    page: 35,
  },
  {
    name: 'Introduction to Economics for IS',
    credits: 6,
    subjectArea: 'business_administration',
    description: 'Introduction to micro- and macroeconomics and economic policy as relevant for information systems.',
    page: 42,
  },
  {
    name: 'Project Management',
    credits: 6,
    subjectArea: 'information_systems',
    description: 'Fundamentals of IT project management including lifecycle, processes, methods and tools.',
    page: 45,
  },
  {
    name: 'Communication and Collaboration Systems',
    credits: 6,
    subjectArea: 'information_systems',
    description: 'Analysis of communication and collaboration technologies, CSCW, and organizational implications.',
    page: 49,
  },
  {
    name: 'Computer Structures and Operating Systems',
    credits: 9,
    subjectArea: 'computer_science',
    description: 'Foundations of computer architecture and operating systems; Von Neumann architecture and OS concepts.',
    page: 52,
  },
  {
    name: 'Data Analysis and Simulation',
    credits: 9,
    subjectArea: 'quantitative_methods',
    description: 'Statistical data analysis and simulation methods; use of software tools like R to model problems.',
    page: 55,
  },
  {
    name: 'Digital Business',
    credits: 6,
    subjectArea: 'information_systems',
    description: 'Overview of digital business models, digital transformation, security and privacy issues; group-based assignments.',
    page: 58,
  },
  {
    name: 'Foundations of Marketing',
    credits: 6,
    subjectArea: 'business_administration',
    description: 'Introductory marketing course covering relationships between marketing, markets, and strategy.',
    page: 61,
  },
  {
    name: 'IT Law',
    credits: 6,
    subjectArea: 'information_systems',
    description: 'Legal aspects of information technology, including e-commerce contracts, IT contracts, data protection, and domain names.',
    page: 63,
  },
  {
    name: 'Project Seminar',
    credits: 12,
    subjectArea: 'information_systems',
    description: 'A practice-oriented project in collaboration with industry; includes literature review, design, and presentations.',
    page: 67,
  },
  {
    name: 'Vertiefungsmodul Wirtschaftsinformatik',
    credits: 9,
    subjectArea: 'information_systems',
    description: 'Specialization in information systems with selected topics from economics, mathematics, or computer science, including a seminar and project.',
    page: 69,
  },
  {
    name: 'Vertiefungsmodul Informatik',
    credits: 9,
    subjectArea: 'computer_science',
    description: 'Specialization in computer science with topics such as networks, distributed systems, mainframe computing, or IT security; includes seminar and presentation.',
    page: 73,
  },
  {
    name: 'Vertiefungsmodul Quantitative Methoden',
    credits: 9,
    subjectArea: 'quantitative_methods',
    description: 'Specialization in quantitative methods with topics such as data analysis, computational intelligence, optimization, time series, and statistical software.',
    page: 76,
  },
  {
    name: 'Vertiefungsmodul BWL',
    credits: 9,
    subjectArea: 'business_administration',
    description: 'Specialization in business administration offering modules such as Advanced Accounting, Insurance Economics, Quantitative Marketing, and Ethics; includes an internship.',
    page: 78,
  },
  {
    name: 'Wissenschaftlich begleitetes Praktikum',
    credits: 9,
    subjectArea: 'information_systems',
    description: 'Scientifically supervised internship with a written report and presentation, applicable to IS studies.',
    page: 81,
  },
  {
    name: 'Bachelorarbeit',
    credits: 12,
    subjectArea: 'information_systems',
    description: 'Bachelor thesis; independent, scientific research culminating in a written thesis and oral defense.',
    page: 85,
  },
] as Array<{
  name: string
  credits: number
  subjectArea: SubjectArea
  description: string
  page: number
}>
